DHI-Roma/gregorovius-frontend

- src/views/LettersIndex.vue
This adds the ability to right-click on a table row in order to open the dataset in a new window/tab.
> feat: Add context menu after right click

- src/components/Comment.vue
- src/components/MultipleSelectAutoComplete.vue
- src/components/SelectAutoComplete.vue
- src/services/table-service.js
- src/store.js
- src/views/LettersIndex.vue
- tests/unit/components/SelectAutoComplete.vue.spec.js
- tests/unit/fixtures/unique-entities.js
- tests/unit/services/table-service.spec.js
- tests/unit/views/LettersIndex.vue.spec.js
We want to be able to filter by mulitple recipients in the LetterIndex.vue
* We introduce another component `MultipleSelectAutoComplete` that handles multi selection (for separation of concerns and testability)
* The filter function in the `LetterIndex` component now relies on store variables for filtering.
> FG-03-08: Enable multi select for recipients

- package.json
- src/services/place-service.js
- src/views/PlacesDetail.vue
- src/views/PlacesIndex.vue
- tests/unit/services/place-service.spec.js
We want to reposition the place type on the place detail page.
We also want to show the place type on the place index view.
> FG-03-12-2: Enable labels on index page

- src/components/CorrespondenceTable.vue
- src/views/PersonsDetail.vue
- tests/unit/fixtures/persons.js
- tests/unit/views/PersonsDetail.vue.spec.js
In the PersonDetail view, we want to show a list of the letters, the person was a correspondence partner in.
* We show that list
* If there is no entry, we don't show the list
> FG-03-11-3: Show correspondences in person detail view

- src/views/PersonsDetail.vue
- tests/unit/fixtures/persons.js
- tests/unit/fixtures/single-person.js
- tests/unit/views/PersonsDetail.vue.spec.js
We want to show notes in the person detail view if they are available
> FG-03-11-5: Show notes in PersonDetail view

- src/assets/xslt/LettersText.xslt
- src/components/PersonsTitle.vue
- src/routes.js
- src/views/PersonsDetail.vue
- src/views/PersonsDetailMultiple.vue
- tests/unit/components/CommentIcon.vue.spec.js
- tests/unit/components/PersonsTitle.vue.spec.js
- tests/unit/fixtures/letters-response.js
- tests/unit/fixtures/persons.js
- tests/unit/views/PersonsDetail.vue.spec.js
- tests/unit/views/PersonsDetailMutliple.spec.js
We want to have a derefencing view for persons, anologous to how the works are dereferenced.
* We added a new view `PersonsDetailMultiple` to show multiple entries at once
* XSLT is adapted to select the right type of view.
> FG-03-11-4: Add multiple persons view

- src/shared/config.js
- src/views/LettersIndex.vue
- tests/unit/views/LettersIndex.vue.spec.js
We want to show a hint for phrase searching.
> FG-03-09: Phrase Search

- src/services/letter-service.js
- src/shared/constants.js
- src/views/LettersDetail.vue
- tests/unit/fixtures/letter-index-item.js
- tests/unit/services/letter-service.spec.js
We want to show a citation hint.
* At the bottom of the `LettersDetailView` component we now show a citation hint.
* You can copy the citation hint with a button press.
> FG-03-07-01: Add citation hint

- .gitignore
- README.md
- env.dist.js
- env.js
- src/shared/config.js
- src/shared/service.js
- src/views/LettersDetail.vue
- src/views/WorksDetail.vue
- src/views/WorksDetailMultiple.vue
We want to have a config file on the top level
> SUPPORT-03: Change config file structure

- src/components/PersonsTitle.vue
- src/services/person-service.js
- src/views/PersonsDetail.vue
- src/views/PersonsIndex.vue
We want to show the birth and death date in the PersonsIndex view. Also the subNameType was not rendered properly depending on the component.
> SUPPORT-05: PersonsDetail & PersonsIndex fixes

- src/assets/xslt/LettersText.xslt
- src/components/ContextMenu.vue
- src/components/CorrespondenceTable.vue
- src/components/LettersText.vue
- src/components/MentionsTable.vue
- src/components/PersonTile.vue
- src/components/PlaceTile.vue
- src/components/WorksIndexTable.vue
- src/mixins/openInNewTabMixin.js
- src/views/LettersDetail.vue
- src/views/LettersIndex.vue
We want to be able to open entities in new tabs by either right-click context menu or a middle mouse click.
> SUPPORT-07: Add new tab functionality

- package-lock.json
- package.json
- src/assets/xslt/LettersText.xslt
- src/components/MentionsTile.vue
- src/components/PersonTile.vue
- src/components/PlaceTile.vue
- src/shared/constants.js
- src/styles/quasar.styl
- src/styles/shared.styl
- src/views/LettersDetail.vue
- src/views/PersonsIndex.vue
We want to show a list of mentioned entities in the LettersDetail view.
> Show mentioned entities

- env.js
- package.json
- src/components/PersonSeeAlsoTable.vue
- src/services/beacon-service.js
- src/views/PersonsDetail.vue
- src/views/Project.vue
On the PersonsDetail view, we want to show references to other resources having info about that person / organization.
> FG-03-13: Show BEACON Findbuch references

- package.json
- src/components/PersonSeeAlsoTable.vue
The seealso references in the PersonsDetail view should be shown a little denser
> FG-03-13-04: Make seealso table denser

- package.json
- src/components/MentionsTable.vue
We want to sort the MentionsTable chronologically, instead of alphabetically.
> SUPPORT-10: Sort MentionsTable chronologically

- package.json
- src/components/CorrespondenceTable.vue
- src/views/PersonsDetail.vue
We also want to show the correspondences chronologically
> SUPPORT-10: Sort correspondence table chronologically

- package-lock.json
- package.json
- public/index.html
- src/layouts/Default.vue
- src/routes.js
- src/shared/additional-literature.js
- src/shared/announcements.js
- src/views/Announcements.vue
- src/views/Project.vue
We want to show announcements, news and further literature.
We added a new route/view under `/announcements`
> SUPPORT-19: Add announcements page

- package.json
- src/shared/announcements.js
- src/views/Announcements.vue
- src/views/Project.vue
> SUPPORT-21: Modify project descriptions and announcements

- src/shared/additional-literature.js
- src/shared/announcements.js
We want to update the announcement page with some links. Additionally some modifications to the literature.
> SUPPORT-24: Update announcements

- src/components/SelectYears.vue
- src/store.js
- src/views/LettersIndex.vue
The year select toggles randomly turned off
Rewrote the feature according to the quasar specs
> SUPPORT-25: Improve year selection

- .eslintrc.js
- .prettierrc
- package-lock.json
- package.json
- src/views/LettersDetail.vue
- We want to use a magnifying glass
- Add VuePhotoZoomPro dependency
- Update prettierrc
> FG-03-14-b: Add magnifying glass to facsimile view

- src/views/LettersDetail.vue
> DHI-GREG-FE-72: Fix issue when trying to open letter directly and apply filters without query params

- src/views/LettersDetail.vue
Mentioned entities weren't taking into account when browsing.
- Changed foreach to for of loop
> DHI-GREG-FE-74: Change loop to allow for return
